site_name: Sense HAT
theme: readthedocs
site_url: https://sense-hat.readthedocs.io/en/latest/
repo_url: https://github.com/astro-pi/python-sense-hat
site_description: Python module to control the Raspberry Pi Sense HAT used in the Astro Pi mission
site_author: Raspberry Pi Foundation
site_dir: readthedocs
#google_analytics: ['UA-46270871-5', 'pythonhosted.org/sense-hat']
nav:
- 'Home': 'index.md'
- 'API Reference': 'api.md'
- 'Examples': 'examples/README.md'
- 'Changelog': 'changelog.md'
